version: '3.8'

volumes:
  n8n_storage:

services:

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db_postgres_rob
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWD}
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
    env_file: .env
    networks:
      - docker-db_rede

networks:
  docker-db_rede:
    external: true
